[package]
name = "nscript-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nscript-semantics = { path = "../nscript-semantics" }
nscript-syntax = { path = "../nscript-syntax" }
rustls = { workspace = true, optional = true }
serde_json.workspace = true
sha2.workspace = true
tungstenite = { workspace = true, optional = true }
wasmi = { version = "0.38", optional = true }

[features]
default = ["real-hosts"]
real-hosts = ["dep:rustls", "dep:tungstenite"]
wasm-engine = ["dep:wasmi"]

[dev-dependencies]
nscript-modules = { path = "../nscript-modules" }
semver.workspace = true

[lints]
workspace = true
