[package]
name = "nscript-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nscript-semantics = { path = "../nscript-semantics" }
nscript-syntax = { path = "../nscript-syntax" }

[lints]
workspace = true
